### ISSUE TITLE
Selection out of image boundaries

### ISSUE THREAD

**Issue by enginer** [w32blaster/gwt-cropper#25]
Hello Guys, looks we have a problem in release 0.5.4. I can select region for cropping out of image boundaries:
![image](https://cloud.githubusercontent.com/assets/1183619/9462747/843cc0b8-4b20-11e5-878a-5a2bd7df8579.png)

Result in coordinates:
![image](https://cloud.githubusercontent.com/assets/1183619/9462809/e37758ea-4b20-11e5-8882-5b78975003e9.png)

Image original size: 2144 x 1424. 
Selection height should be less or equals 1424 and Y coordinate should be more or equals 0.

**Comment by w32blaster** [comment]
mmm... It seems that I forgot to test the last pull request with square selection... I will try to fix that today. Sorry for that.

**Comment by thoepfner** [comment]
@enginer I tried to reproduce that, but it appears to be working fine for me. Can you provide steps to reproduce the problem, please?

**Comment by enginer** [comment]
@thoepfner I think you need to pay attention what my original image match bigger than cropper working region.
Video with reproducing screen record https://www.youtube.com/watch?v=yyk5wz-pBDk

**Comment by w32blaster** [comment]
@enginer Hey, I tried to reproduce your case but unfortunately I failed to repeat your steps. I played with different combinations but it seems forking for me. I tried various aspect ratios, I used the picture much more bigger than cropper size and selection remains within widget borders. Can you please provide more information how to reproduce this bug, please? Thanks.

In my case it looks like this:
![cropper_selection](https://cloud.githubusercontent.com/assets/6038179/9475890/77885e90-4b61-11e5-8012-8c87c1768997.jpg)

**Comment by enginer** [comment]
@thoepfner Yes, it is not trivial to reproduce this behavior, I can do this only for (this image)[http://c2n.me/3mDUIZq]. I think the main point it is moving and resizing of selection, try to copy my movement on screen record https://www.youtube.com/watch?v=yyk5wz-pBDk. 
Thank You for Your tryings :)!

**Comment by w32blaster** [comment]
Which browser do you use? Can you provide a code snippet how do you declare Cropper in your code and how you attach it to a panel (may be there is something specific that we forgot to keep in eyes)?

**Comment by enginer** [comment]
I am using Firefox 24.7.0, and code:

attachment

                cropper = new GWTCropper(file.getImageUrl());
                cropper.setWidth(300);
                cropper.setAspectRatio(1);
                cropper.registerPreviewWidget(view.getPreview());
                view.getWrapper().add(cropper);

ui.xml:

    <ui:UiBinder xmlns:ui='urn:ui:com.google.gwt.uibinder'
                 xmlns:g='urn:import:com.google.gwt.user.client.ui'
                 xmlns:cropper="urn:import:com.google.code.gwt.crop.client"
                 xmlns:fu="urn:import:com.store.client.application.widget.fileupload">
    
        <ui:with field="res" type="com.store.client.resources.AppBundle"/>
    
        <ui:style>
            .wrapper {
                width: 300px;
                min-height: 150px;
                border: 1px solid #d4d4d4;
                border-radius: 3px;
                text-align: center;
                display: inline-block;
                padding: 5px;
                color: #c6c6c6;
            }
        </ui:style>
    
        <g:FlowPanel>
            <fu:FileUploader ui:field="uploader"/>
                <g:HorizontalPanel spacing="20">
                    <g:cell>
                        <g:SimplePanel ui:field="wrapper" styleName="{style.wrapper}" />
                    </g:cell>
                    <g:cell>
                        <g:HTMLPanel>
                            <h1>Preview</h1>
                            <cropper:GWTCropperPreview dimension="HEIGHT" value="100" ui:field="preview" />
                        </g:HTMLPanel>
                    </g:cell>
    
                </g:HorizontalPanel>
        </g:FlowPanel>
    </ui:UiBinder>

**Comment by w32blaster** [comment]
Firefox 24.7.0? Come on, man! Current version is 40.0 :)

Ok, thank you for the code snippet, I will try it at home. But I don't see anything suspicious in your so far... Looks correct.

**Comment by enginer** [comment]
> Firefox 24.7.0? Come on, man! Current version is 40.0 :)

I use this version only for GWT debug mode, have some problems with GWT plugin in newest versions...

**Comment by w32blaster** [comment]
@enginer  Is this issue still actual? Otherwise I would close this ticket

**Comment by enginer** [comment]
Guys, thanks a lot, a cannot anymore reproduce a bug! Sorry for a so late response.
