### ISSUE TITLE
LoadHandler should be added before setting the URL of the image

### ISSUE THREAD

**Issue by idegregorio** [w32blaster/gwt-cropper#28]
Thanks for your project.

In the GWTCroppert.addCanvas the LoadHandler should be added before the URL is set  to guarantee that it is called. Rather than:

``` java
image = new Image(url);
image.addLoadHandler(new LoadHandler(){...});
```

it should read:

``` java
image = new Image();
image.addLoadHandler(new LoadHandler(){...});
image.setUrl(url);
```

**Comment by w32blaster** [comment]
Thanks for the code review! 

Is this issue ticket just a recommendation or the existing code causes some real failures in your code?
