### ISSUE TITLE
Links to Demo are broken

### ISSUE THREAD

**Issue by jeb62868** [w32blaster/gwt-cropper#30]
The links to your demo on the Github page:

https://github.com/w32blaster/gwt-cropper/wiki/Usage

and your web site:

http://gwt-cropper.co.uk

both point to a broken link here:

http://wiki.gwt-cropper.googlecode.com/hg/demo/Application.html

They need to be updated to point here:

http://gwt-cropper.co.uk/demo/Application.html

**Comment by w32blaster** [comment]
Whoops, that is because of migrating from Google Code. I updated all the links in the aforementioned pages and I also checked other pages in the Wiki. Now all the links seems to be correct.

Thank you for this issue ticket! Have a nice day!
