### ISSUE TITLE
Demo code

### ISSUE THREAD

**Issue by andreififiita** [w32blaster/gwt-cropper#34]
Is there anywhere where we could see the demo code? The demo links are broken

**Comment by w32blaster** [comment]
Hey, thank you for the issue submitting. I renewed the domain, it will be accessible soon.

But few other examples you can find in the wiki, for example, here: https://github.com/w32blaster/gwt-cropper/wiki/How-To-Use-Preview-Widget

**Comment by w32blaster** [comment]
hey. the domain http://gwt-cropper.co.uk/ is up again. Is there anything else I could help you with?

**Comment by andreififiita** [comment]
It is working but the demo links are broken: http://wiki.gwt-cropper.googlecode.com/hg/demo/Application.html

**Comment by w32blaster** [comment]
oh, I see. Ok, I will fix broken links shortly, but for now, please refer to these correct links for demos:
- http://gwt-cropper.co.uk/demo/Application.html
- http://gwt-cropper.co.uk/demo/Application2.html

**Comment by andreififiita** [comment]
Also, I believe that the crop dragging does not account for the scroll of
the window (i noticed that when dragging it behaves strangely if there is a
window scroll). And also, you could add an on drag handler, to get the
selection in real time and update a preview in realtime while dragging.
Thank you.

**Comment by w32blaster** [comment]
I am afraid, I don't have time for that :disappointed_relieved: Sorry :sob:
